[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

# Explicitly disable Node.js processing
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--no-optional"

# No plugins needed for static site
[build.processing]
  skip_processing = true